# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:15
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spitch', '0002_auto_20170527_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='spitch',
            name='photo',
            field=apps.core.fields.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='spitch',
            name='video',
            field=apps.core.fields.FileField(null=True, upload_to=''),
        ),
    ]
