# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitch', '0003_auto_20170606_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='spitch',
            name='color',
            field=models.IntegerField(choices=[(1, 'Violet')], default=1),
        ),
    ]
