# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 16:41
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitch', '0004_spitch_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='spitch',
            name='thumb',
            field=apps.core.fields.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spitch',
            name='color',
            field=models.IntegerField(choices=[(1, 'Violet'), (2, 'Orange'), (3, 'Rouge'), (4, 'Vert'), (5, 'Rose'), (6, 'Bleu')], default=3),
        ),
    ]
