# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitch', '0005_auto_20170606_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spitch',
            name='color',
            field=models.IntegerField(choices=[(1, 'Violet'), (2, 'Orange'), (3, 'Rouge'), (4, 'Vert'), (5, 'Rose'), (6, 'Bleu')], default=5),
        ),
    ]
