# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spitch', '0006_auto_20170606_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='spitch',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='spitch',
            name='color',
            field=models.IntegerField(choices=[(1, 'Violet'), (2, 'Orange'), (3, 'Rouge'), (4, 'Vert'), (5, 'Rose'), (6, 'Bleu')], default=1),
        ),
        migrations.AddField(
            model_name='like',
            name='spitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='spitch.Spitch'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('spitch', 'user')]),
        ),
    ]
