# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 15:34
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spitch', '0007_auto_20170703_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='spitch',
            name='spitch_transcoded',
            field=apps.core.fields.FileField(null=True, upload_to=''),
        ),
    ]
