# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spitch', '0009_auto_20170718_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('spitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='spitch.Spitch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('spitch', 'user')]),
        ),
    ]
