# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 14:24
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spitch', '0010_auto_20170801_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spitch',
            name='video',
            field=apps.core.fields.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
