# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='receivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
