# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_ask_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='receivers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
