# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_auto_20170606_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
