# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 10:06
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=apps.core.fields.ImageField(blank=True, default='default.jpg', upload_to='', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
