# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20170421_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookfriend',
            name='follow',
        ),
    ]
