# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20170703_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
