# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170417_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_id',
        ),
        migrations.AddField(
            model_name='user',
            name='snid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
