# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170420_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='snid',
            new_name='idsn',
        ),
    ]
