# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170420_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
