# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20170504_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='FR', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
