# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20170504_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
