# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome',
            field=models.BooleanField(default=True),
        ),
    ]
